services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"     # RTSP
      - "8555:8555"     # RTSPS
      - "9997:9997"     # API
      - "9998:9998"     # Metrics
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./recordings:/recordings
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
        reservations:
          cpus: '2'
          memory: 2G
    environment:
      - MTX_PROTOCOLS=tcp
    # üëá ‡πÑ‡∏°‡πà‡∏ï‡πâ‡∏≠‡∏á‡πÉ‡∏ä‡πâ network custom ‡πÅ‡∏•‡πâ‡∏ß
    network_mode: bridge

  backendcam:
    container_name: backendcam
    build:
      context: .
      dockerfile: Dockerfile
    image: backendcam:latest
    depends_on:
      - mediamtx
    ports:
      - "8080:8080"
    environment:
      RTSP_HOST: 127.0.0.1
    volumes:
      - ./hls:/hls
    restart: unless-stopped
    # üëá ‡πÉ‡∏ä‡πâ host network ‡πÄ‡∏û‡∏∑‡πà‡∏≠‡πÉ‡∏´‡πâ‡πÄ‡∏Ç‡πâ‡∏≤‡∏ñ‡∏∂‡∏á 127.0.0.1:8554 ‡πÑ‡∏î‡πâ
    network_mode: host